// Code generated by goctl. DO NOT EDIT.

export interface LoginReq {
}

export interface LoginReqParams {
	enterprise_id: number
	username: string
	password: string
}

export interface LoginReply {
	id: number
	name: string
	gender: string
	role: string
	access_token: string
	access_expire: number
}

export interface InsertStafferReq {
	username: string
	workshop_id: number
	name: string
	role: string
	gender: string
	phone_number: string
	email: string
	address: string
	remark: string
}

export interface InsertStafferReply {
	id: number
	message: string
	password: string
}

export interface UpdateStafferInfoReq {
	id: number
	username?: string
	workshop_id?: number
	name: string
	role?: string
	gender?: string
	phone_number?: string
	email?: string
	address?: string
	remark?: string
}

export interface UpdateStafferInfoReply {
	message: string
	changed_fields: Array<string>
}

export interface StafferInfo {
	id: number
	username: string
	workshop_id: number
	name: string
	role: string
	gender: string
	phone_number: string
	email: string
	address: string
	remark: string
}

export interface GetStafferListByEnterpriseReq {
}

export interface GetStafferListByEnterpriseReqParams {
	page_number: number
	page_size: number
}

export interface GetStafferListByEnterpriseReply {
	message: string
	count: number
	staffer_list: Array<StafferInfo>
}

export interface GetStafferListByWorkshopReq {
}

export interface GetStafferListByWorkshopReqParams {
	workshop_id: number
	page_number: number
	page_size: number
}

export interface GetStafferListByWorkshopReply {
	message: string
	count: number
	staffer_list: Array<StafferInfo>
}

export interface UpdateStafferPasswordReq {
}

export interface UpdateStafferPasswordReqParams {
	old_password: string
	new_password: string
}

export interface UpdateStafferPasswordReply {
	message: string
}

export interface ResetStafferPasswordReq {
}

export interface ResetStafferPasswordReqParams {
	id: number
}

export interface ResetStafferPasswordReply {
	message: string
	password: string
}

