// Code generated by goctl. DO NOT EDIT.

export interface InsertWorkshopReq {
	name: string
	address?: string
	phone_number?: string
	manager_id?: number
	remark?: string
}

export interface InsertWorkshopReply {
	id: number
	message: string
}

export interface UpdateWorkshopInfoReq {
	id: number
	name?: string
	address?: string
	phone_number?: string
	manager_id?: number
	remark?: string
}

export interface UpdateWorkshopInfoReply {
	message: string
	changed_fields: Array<string>
}

export interface DeleteWorkshopReq {
	id: number
}

export interface DeleteWorkshopReply {
	message: string
}

export interface WorkshopInfo {
	id: number
	name: string
	address: string
	phone_number: string
	manager_id: number
	remark: string
}

export interface GetWorkshopListReq {
	pn: number
	ps: number
}

export interface GetWorkshopListReply {
	message: string
	workshop_list: Array<WorkshopInfo>
}

export interface CreateEnterpriseReq {
	name: string
	boss_name: string
	boss_password: string
	address?: string
	remark?: string
}

export interface CreateEnterpriseReply {
	id: number
	message: string
}

export interface UpdateEnterpriseInfoReq {
	name?: string
	address?: string
	remark?: string
}

export interface UpdateEnterpriseInfoReply {
	message: string
	changed_fields: Array<string>
}

export interface DeleteEnterpriseReq {
	password: string
}

export interface DeleteEnterpriseReply {
	message: string
}

export interface GetEnterpriseIdByNameReq {
}

export interface GetEnterpriseIdByNameReqParams {
	name: string
}

export interface GetEnterpriseIdByNameReply {
	id: number
}

